### ISSUE TITLE
Failure trying to run stunner-editor.

### ISSUE THREAD

**Issue by krakzk** [apache/incubator-kie-tools#1220]
I have tried the following steps to start the stunner in my localhost. 
Clone the repo, ran the bootstrap and build commands for stunner-editors which were success.
Then I followed

 change to the kie-tools/packages/stunner-editors/kie-wb-common-stunner root folder
**_run mvn clean install -DskipTests -Dgwt.compiler.skip=true_**
Build the webapp:
Dev: **_mvn -T 8C clean install -DskipTests=true -Ddev_** 

Those too were success.
Then i ran the **_mvn gwt:run_**  command, but getting the below error:

**[ERROR] Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.9.0:run (default-cli) on project kie-wb-common-stunner: The parameters 'runTarget' for goal org.codehaus.mojo:gwt-maven-plugin:2.9.0:run are missing or invalid**

**Comment by romartin** [comment]
Hello @krakzk 

This error is because the command `mvn gwt:run` is being executed in the `kie-wb-common-stunner` root, but the root module doesn't contain itself a gwt app module. 

Just run the `mvn gwt:run` command in the [kie-wb-common-stunner-bpmn-kogito-runtime](https://github.com/kiegroup/kie-tools/tree/main/packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime) root instead.

Sorry for the inconveniences, as I see the the [README](https://github.com/kiegroup/kie-tools/tree/main/packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime#running-in-sdm) is not specifying to change the root. I am just going to create a PR to fix the readme :)

Thanks for your feedback!

**Comment by romartin** [comment]
PR created: https://github.com/kiegroup/kie-tools/pull/1234

**Comment by romartin** [comment]
Thanks  @krakzk for the feedback. Closing the issue for now. Please feel free to reopen or create a new ticket if any further issues or Qs. Thanks!
