### ISSUE TITLE
Add Custom Actors in Dropdown search of BPMN User Task

### ISSUE THREAD

**Issue by krakzk** [apache/incubator-kie-tools#1224]
This is a question, not basically an issue.

I am new to kie-tools environment. Was trying around changing various properties for the BPMN editor.

Trying to find a way to inject my set of actors and groups to the User Tasks.
I am running the kogito-bpmn-runitime app test.html.

Any help would be appreciated.

**Comment by hasys** [comment]
Hello @krakzk,

thank you for your question!

Some high level overview of the way forms works in Stunner:
there exist:
- [model classes](https://github.com/kiegroup/kie-tools/blob/e7cee444fe6cc55d47606e387ba49776da9c6f10/packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/property/task/UserTaskExecutionSet.java): like Actors or Groupid -> those are storing the state for a field
- provider classes: populate the model
- renderer classes: renders the model in some way in the html (eg: by using custom renderer)

For Actors and Groups there is a bit difference because they share the same Form element.
Forms code is located [here](https://github.com/kiegroup/kie-tools/tree/4251fbbbc8f8d546a569be32462be709cc925eef/packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assigneeEditor).
You can see `widget` package which actually a renderer and `*SearchService` which is doing what you actually need there.

Take a look at `search` method which is called by the Form element on load and populating predefined values. Just add values to [this collection](https://github.com/kiegroup/kie-tools/blob/4251fbbbc8f8d546a569be32462be709cc925eef/packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-client/src/main/java/org/kie/workbench/common/stunner/bpmn/client/forms/fields/assigneeEditor/AssigneeLocalSearchService.java#L55) and it should be it.

Let me know if you have any further questions, thank you!

**Comment by moaazabir** [comment]
Hello @hasys ,

I have Users and Groups available in keycloak, is there a way where it can be integrated with the Live Search?

**Comment by romartin** [comment]
Hey @moaazabir 

I understand you're using the process editor in the Business Central. Please let me know otherwise.

In that case, as far as I remember, the `actors` and `groups` fields are actually consuming the users / groups from the `Users Management` subsystem. By default, if nothing configured, the subsystem reads the own wildfly realm (properties files). But you can configure it properly, by making the users management to consume your keycloak realm, instead of the properties files, so both fields will automatically be populated with the information from the keycloak server, no need for code customizations, it's just about configuring your workbench. 

For more information about how to configure the workbench users management see [1]

Also, you can find more detailed technical information about the security management and, in concrete, the keycloak security provider at  [2]

[1] https://docs.jbpm.org/7.73.0.Final/jbpm-docs/html_single/#_keycloak_and_the_business_centrals_security_administration_area

[2] https://github.com/kiegroup/appformer/tree/main/uberfire-extensions/uberfire-security/uberfire-security-management

CC @hasys

**Comment by krakzk** [comment]
@moaazabir  Thank you for raising the question.
@romartin  What if I am running the stunner editor as a standalone? And i get the Users/Actors and Groups as a JSON response invoking an API?

**Comment by krakzk** [comment]
The solution final is present in the below link
https://stackoverflow.com/questions/73698809/add-custom-actors-and-groups-in-kogito-user-task/73715252?noredirect=1#comment130192756_73715252
