### ISSUE TITLE
Reload setup for BPMN runtime editor in Intellij

### ISSUE THREAD

**Issue by krakzk** [apache/incubator-kie-tools#1251]
I have Intellij 2021.3.2 Community edition installed in my system. But I am unable to follow up the setting to get the reload and on the go update for the BPMN editor code (even only the CSS would do).
Is there any steps I could follow ?
The doc found in the repo seems to be for Intellij 15 and not able to set that up either.

Using different editor like VSCode is also accepatble, if any setup steps to be followed can be provided

**Comment by romartin** [comment]
Hello @krakzk 

Please take a look at the updated [README](https://github.com/kiegroup/kie-tools/blob/main/packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime/README.md) for running the bpmn editor showcase app. The configurations for making the app to run are quite simple, and they do apply also for latest IntelliJ IDEA versions (as we're internally also using it).

In general I am using these simple steps:
1.- Create new maven project by importing from [kie-wb-common-stunner](https://github.com/kiegroup/kie-tools/tree/main/packages/stunner-editors/kie-wb-common-stunner) root (File -> Import project from existing sources -> choose maven project)
2.- Create the GWT run/app configuration as described in the README
3.- Right click on root folder -> maven -> reload project
4.- Menu Build -> Rebuild project
5.- Click on Run icon to start the GWT App configured in step 2

This way, all stunner and BPMN modules are part of the project, so you can change any file and hot reload plugin will detect properly.

In case you still are running into issues, can you please share more feedback in order to figure out what the issue is:
1. Share screenshots or info about with your GWT run/debug config
2. Share screenshots of info about the project structure

Let's keep in touch!
Thanks!

**Comment by krakzk** [comment]
Not able to get the GWT configuration setting. 
IntelliJ IDEA 2021.3.2 (Community Edition) -  This my IDE spec.
Tried installing the GWT support plugin available in the Marketplace, still no success.

Java 17.0.2 is being used

**Comment by krakzk** [comment]
Any update on this? 
To setup the env in the latest Intellij Community version

**Comment by inodeman** [comment]
Hi @krakzk the is currently not a plugin supporting GWT on the Community Edition, the recommended way of running it is through CLI. Here are some steps

1) Go to :/kie-tools/packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-kogito-runtime
2) execute mvn clean gwt:run
* The hot reload feature should work fine 
* There have been some issues on MAC OS where GWT.log does not work well
You can of course use IntelliJ CE or any other editor to do the changes and the hot reload will work when you reload the page.
Let me know if this worked for you
