### ISSUE TITLE
Unable to load bpmn2 files in vscode

### ISSUE THREAD

**Issue by rahgadda** [apache/incubator-kie-tools#133]
Hi Team,

I tried installing 0.4.0 (alpha) version and unable to load persons.bpmn2 file i my VSCode.
I have attached screenshots of the issue that I am facing.

![Issue](https://user-images.githubusercontent.com/13075415/79549342-7db98400-80b4-11ea-97ad-c0f41a08011e.png)

Regards,
Rahul

**Comment by ederign** [comment]
Hi @rahgadda how are you today?

We are packing our extension with the new VSCode Custom webview proposed API. In order to use it, via command line you have to run VS Code with the following command:

OSX: code --enable-proposed-api kiegroup.vscode-extension-pack-kogito-kie-editors
Linux/Windows: code --enable-proposed-api kiegroup.vscode-extension-pack-kogito-kie-editors


I hope it helps

EI

**Comment by ederign** [comment]
Feel free to reopen if this doesn't fix for you! :)

**Comment by rahgadda** [comment]
Sorry @ederign I tried to open my folder with `code --enable-proposed-api kiegroup.vscode-extension-pack-kogito-kie-editors` but still, I am getting a blank screen.
![image](https://user-images.githubusercontent.com/13075415/79626487-249e2e80-814e-11ea-8eeb-33e279c34ccc.png)

Is there anything I have to do on VSCode to make it running.
If u see in my screenshot, all my bpmn, bpmn2 and dmn files are getting opened in **Kie Kogito Editors** view only.

Please help. I know to work with VSCode but not an expert.
