### ISSUE TITLE
Included models in standalone DMN editor

### ISSUE THREAD

**Issue by mariokorte** [apache/incubator-kie-tools#2388]
We use the standalone DMN editor JS-library in our own webapp and use the provided api to load models into the editor.

We now want to use the feature of included models, but the dialogue to select models to include ist always empty (of course). I want to provide models to include in this dialogue via api functions, but I seem to be unable to find any such methods. 

Is there something I am missing (unfortunately the API seems to be somewhat minimal documented) or is this plainly not supported?

**Comment by mariokorte** [comment]
Okay, i've found out it should be possible to submit additional resources as a map this way:

`
const editor = DmnEditor.open({
  container: document.getElementById("dmn-editor-container"),
   initialContent: Promise.resolve("<your-dmn-content>"),
  readOnly: false,
  resources: new Map([
    [
      "MyIncludedModel.dmn",
      {
        contentType: "text",
        content: Promise.resolve("<your-included-model-content>")
      }
    ]
  ])
});
`

Problem is, that whatever I add as resources, they never show up in the list of models to include. Is there still something I miss?

**Comment by tiagobento** [comment]
What version of the Standalone Editors are you using, and can you please provide a reproducer?

You're right that the API is minimally documented, right now the only docs we have on that API are on the README itself...
https://www.npmjs.com/package/@kie-tools/kie-editors-standalone

**Comment by mariokorte** [comment]
@tiagobento while building the reproducer I noticed that the list to chose the models to include from lists only models that have a different namespace than the current model in the editor. This is intended I guess?

In the end it seems this is the problem I am seeing right now.

**Comment by tiagobento** [comment]
@mariokorte Yeah, I understand how that is confusing, but the `namespace` attribute has to actually be globally unique. This is the primary identifier of a DMN file, as when importing one DMN into another, the namespace is actually the primary key.

Of course we should have some sort of error or warning when multiple models with the same namespace are in the same "context" (in this case, an instance of the DMN Standalone Editor).

Since we're considering the development of the classic DMN Editor stopped right now, to make way for a new DMN Standalone Editor based on the new DMN Editor, I'm going to close this ticket, but will keep that in mind when developing the API for the new DMN Standalone Editor.

Let us know if there's anything else related to this.
