### ISSUE TITLE
BPMN:Property

### ISSUE THREAD

**Issue by ArvindGundimajalu** [apache/incubator-kie-tools#743]
how do I add a BPMN:Property through the editor?
If I use the properties advanced option its adding a meta tag

**Comment by romartin** [comment]
Hello @ArvindGundimajalu 

You mean adding a new field in some of the BPMN domain model objects? If so, lemme explain.

The main goal for _Metadata Attributes_, in the _Advanced Data_ section, is for adding any key-value pair which you can futther use on the runtime execution, but it's not itself being exposed (neither serialized in the BPMN file) as a concrete "new" field for the target object (task, whatever). Anyway, this field is useful because you can store metadata there, also it is being ported in the BPMN file , and use it on your runtime enviornment.

On he other hand, each model object, for instance a task, has a set of fields, each one showing as a separate field in the forms (look a tthe right panel _Properties_). Those fields usually are following the BPMN spec as well. These fields are being modeled as Java beans, in the core of the BPMN editor, see [1] and check all class fields annotated with the `@Property` annotation. 
So if you want to add fields at this level, you'll have to add new fields in the java class, and also I understand update the actual marshallers code for its proper serialization. It means you have to deal with the given repo [1] and use Java/GWT in order to do this. If at some point you're interested on, there are actually README's about how to build the repository and so you can play with it.  

Hope it helps!
Thanks

[1] https://github.com/kiegroup/kie-tools/blob/main/packages/stunner-editors/kie-wb-common-stunner/kie-wb-common-stunner-sets/kie-wb-common-stunner-bpmn/kie-wb-common-stunner-bpmn-api/src/main/java/org/kie/workbench/common/stunner/bpmn/definition/Lane.java#L81

**Comment by StephenOTT** [comment]
@romartin is there plans to move metadata out of the `drools` namespace in the xml to create a bit cleaner structure?  when reviewing the xml it throws readers off when seam "drools"/rule engine references against a bpmn process that does not invoke rules.

**Comment by romartin** [comment]
@StephenOTT I should properly confirm but I think it makes sense what you mention. Anyway let you know that we're actually working on a complete new set of BPMN marshallers, for short term delivery, and I guess most of the namespaceing weird issues are being fixed there.

@hasys can you please check this issue and provide your feedback? Are we changing this in some way on the new implementations?

Thanks in advance!

**Comment by ederign** [comment]
For better backlog organization, we are now tracking this at: https://issues.redhat.com/browse/KOGITO-7004
