### ISSUE TITLE
button scaling not working with zoom in process editor - vs code

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#759]
<img width="992" alt="image" src="https://user-images.githubusercontent.com/1994838/149541381-a7cf7157-9210-44ae-b034-3bd7117092d3.png">

when you zoom out, the buttons get very small rather than scaling.

**Comment by romartin** [comment]
Agree @StephenOTT , it's a known issue, not sure if reported althogh... lemme delgate this properly and thanks for reporting

**Comment by romartin** [comment]
@inodeman Can you please check if the updates on the PR ![1], which implies moving the toolbox implementation out from the main layer, are in some way affected by the user defined transform (in concrete scale/zoom)?

Otherwise, can you please open a new issue for this and let me know so we can priortize? 

Thanks in advance!
[1] https://github.com/kiegroup/kie-tools/pull/794

**Comment by inodeman** [comment]
Hi @romartin @StephenOTT I have created a ticket in order to track it and change the behavious. https://issues.redhat.com/browse/KOGITO-6670

**Comment by romartin** [comment]
ok thanks @inodeman .

**Comment by ederign** [comment]
For better backlog organization, we are now tracking this only at https://issues.redhat.com/browse/KOGITO-6670
