### ISSUE TITLE
Typo `AdvancedData` should be `Advanced Data`?

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#764]
using vs code latest release.

In the Properties tab the Advanced Data section reads as "AdvancedData"

<img width="520" alt="image" src="https://user-images.githubusercontent.com/1994838/149631969-b8ae1ecd-f5c6-4a1a-950b-d9d418c1287f.png">

**Comment by romartin** [comment]
thanks for reporting @StephenOTT , it's noticeable that the translation is not being applied properly... 

@Josephblt Could you please, once you have a while, try to just fix this literal please? Otherwise, if you don't have a chance right now, let's report the issue and assign to ourselves.

Thanks!

**Comment by Josephblt** [comment]
Hello @StephenOTT, thanks for the report. 

Here is the Jira to track this issue:
https://issues.redhat.com/browse/KOGITO-6673

Here is the PR that fixes it:
https://github.com/kiegroup/kie-tools/pull/817

@romartin, @StephenOTT if you guys could please review it that would be great. Thanks.
