### ISSUE TITLE
Sequence Flow selection is too aggressive and causes un-intended line adjustments

### ISSUE THREAD

**Issue by StephenOTT** [apache/incubator-kie-tools#766]
using vs-code.  When select a sequence flow, the first click is most often to check the line's configuration, but the circle that adds a new node into the line for line adjustments is too aggressive and causes the line to move or change position when the user only wants to select the line.

**Comment by romartin** [comment]
Thanks for reporting @StephenOTT .

This issue is actually being fixed as part of some work on lines, see [1]. Once the PR is merged, this issue will be gone. So please keep an eye on the further releases and the PR. Sorry for the inconveniences!

Thanks

[1] https://github.com/kiegroup/kie-tools/pull/776

**Comment by StephenOTT** [comment]
Thanks

**Comment by romartin** [comment]
Np, thanks for the feedback! Let's try to stay with this ticket open until you can confirm it's closed (once new release comes)

**Comment by ederign** [comment]
For better tracking and backlog organization, we are following this issue only at https://issues.redhat.com/browse/KOGITO-5529
